# Generated by Django 4.2.1 on 2023-05-20 04:25

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo', models.IntegerField(choices=[(1, 'Administrador'), (2, 'Cliente')], default=1)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Listado de usuarios',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('imagen', models.CharField(max_length=512)),
                ('cantidad', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Articulos del negocio',
                'verbose_name_plural': 'Articulos',
                'db_table': 'Articulo',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carrito de compra',
                'verbose_name_plural': 'Carritos',
                'db_table': 'Carrito',
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
            ],
            options={
                'verbose_name': 'Tipos de envios disponibles',
                'verbose_name_plural': 'Envios',
                'db_table': 'Envio',
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=4, max_length=4)),
                ('fecha_vencimiento', models.DateField()),
            ],
            options={
                'verbose_name': 'Ofertas de articulos',
                'verbose_name_plural': 'Ofertas',
                'db_table': 'Oferta',
            },
        ),
        migrations.CreateModel(
            name='TipoArticulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Tipos de articulos disponibles',
                'verbose_name_plural': 'TipoArticulos',
                'db_table': 'TipoArticulo',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('comprobante', models.IntegerField()),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enbalde.carrito')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enbalde.envio')),
            ],
            options={
                'verbose_name': 'Listado de Ventas',
                'verbose_name_plural': 'Ventas',
                'db_table': 'Venta',
            },
        ),
        migrations.CreateModel(
            name='Seleccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enbalde.articulo')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enbalde.carrito')),
            ],
            options={
                'verbose_name': 'Seleccion de articulos',
                'verbose_name_plural': 'Selecciones',
                'db_table': 'Seleccion',
            },
        ),
        migrations.CreateModel(
            name='ArticulosEnOferta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enbalde.articulo')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enbalde.oferta')),
            ],
            options={
                'verbose_name': 'Articulos en Oferta',
                'verbose_name_plural': 'ArticulosEnOferta',
                'db_table': 'ArticulosEnOferta',
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enbalde.tipoarticulo'),
        ),
    ]
