# Generated by Django 4.2.1 on 2023-05-18 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enbalde', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoarticulo',
            options={'verbose_name': 'Tipos de articulos disponibles', 'verbose_name_plural': 'TipoArticulos'},
        ),
        migrations.AlterModelTable(
            name='tipoarticulo',
            table='TipoArticulo',
        ),
    ]
