# Generated by Django 4.2.1 on 2023-05-26 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enbalde', '0002_alter_articulo_cantidad_alter_articulo_costo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='imagen',
        ),
    ]
