# Generated by Django 4.2.1 on 2023-05-19 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enbalde', '0002_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='tipo_usuario',
            new_name='tipo',
        ),
    ]
