# Generated by Django 4.2.1 on 2023-05-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enbalde', '0003_oferta_ofertaarticulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_usuario', models.IntegerField()),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=40)),
                ('clave', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=45)),
                ('observaciones', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Listado e usuarios',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
            },
        ),
    ]
