# Generated by Django 4.2.1 on 2023-05-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enbalde', '0004_articulo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Apellido'),
        ),
    ]
