# Generated by Django 4.2.1 on 2023-05-18 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enbalde', '0005_alter_ofertaarticulo_options_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seleccion',
            fields=[
                ('id_seleccion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=0, max_length=10)),
                ('id_articulos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enbalde.producto')),
            ],
            options={
                'verbose_name': 'Selección de Productos',
                'verbose_name_plural': 'Selecciones',
                'db_table': 'Selección',
            },
        ),
    ]
