# Generated by Django 4.2.1 on 2023-06-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enbalde', '0006_alter_venta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='comprado',
            field=models.BooleanField(default=False),
        ),
    ]
