# Generated by Django 4.2.1 on 2023-05-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enbalde', '0006_seleccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seleccion',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
