# Generated by Django 4.2.1 on 2023-06-08 02:02

from django.db import migrations, models
import enbalde.models


class Migration(migrations.Migration):

    dependencies = [
        ('enbalde', '0008_alter_carrito_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='fecha_vencimiento',
            field=models.DateTimeField(validators=[enbalde.models.aceptar_solo_fechas_futuras]),
        ),
    ]
