# Generated by Django 4.2.1 on 2023-06-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enbalde', '0009_alter_oferta_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='articulos',
            field=models.ManyToManyField(to='enbalde.articulo'),
        ),
    ]
