# Generated by Django 4.2.1 on 2023-06-12 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enbalde', '0010_oferta_articulos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='articulos',
            new_name='articulo',
        ),
    ]
