# Generated by Django 4.2.1 on 2023-06-12 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enbalde', '0011_rename_articulos_oferta_articulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='articulo',
            new_name='articulos',
        ),
    ]
