# Generated by Django 4.2.1 on 2023-06-12 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enbalde', '0012_rename_articulo_oferta_articulos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticulosEnOferta',
        ),
    ]
