# Generated by Django 4.2.1 on 2023-06-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enbalde', '0013_delete_articulosenoferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='pago',
            field=models.IntegerField(choices=[(1, 'Efectivo A Pagar'), (2, 'Efectivo Pagado'), (3, 'Enbalde Pago')], default=1),
        ),
        migrations.AddField(
            model_name='venta',
            name='transaccion',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
