-- MySQL Script generated by MySQL Workbench
-- dom 07 may 2023 15:03:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema enbalde
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `enbalde` ;
CREATE SCHEMA IF NOT EXISTS `enbalde` DEFAULT CHARACTER SET utf8mb4 ;
USE `enbalde` ;

-- -----------------------------------------------------
-- Table `enbalde`.`Presentaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enbalde`.`Presentaciones` (
  `id_presentaciones` INT NOT NULL,
  `nombre` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id_presentaciones`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `enbalde`.`TipoArticulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enbalde`.`TipoArticulos` (
  `id_articulos` INT NOT NULL,
  `nombre` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id_articulos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `enbalde`.`Articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enbalde`.`Articulos` (
  `id_articulos` INT NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `tipo` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` DOUBLE NOT NULL,
  `costo` DOUBLE NOT NULL,
  `uni_medida` INT NOT NULL,
  `presentacion` INT NOT NULL,
  `imagen` VARCHAR(512) NOT NULL,
  `alicuota` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id_articulos`),
  INDEX `fk_tipo_art_idx` (`tipo` ASC) VISIBLE,
  INDEX `fk_presen_idx` (`presentacion` ASC) VISIBLE,
  CONSTRAINT `fk_presentacion`
    FOREIGN KEY (`presentacion`)
    REFERENCES `enbalde`.`Presentaciones` (`id_presentaciones`),
  CONSTRAINT `fk_tipo_articulo`
    FOREIGN KEY (`tipo`)
    REFERENCES `enbalde`.`TipoArticulos` (`id_articulos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `enbalde`.`TipoComprobantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enbalde`.`TipoComprobantes` (
  `id_tipo_comprobantes` INT NOT NULL,
  `nombre` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id_tipo_comprobantes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `enbalde`.`Comprobantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enbalde`.`Comprobantes` (
  `id_comprobantes` CHAR(3) NOT NULL,
  `descripcion` VARCHAR(60) NOT NULL,
  `tipo` INT NOT NULL,
  `signo` CHAR(1) NOT NULL,
  PRIMARY KEY (`id_comprobantes`),
  INDEX `fk_tipo_compro_idx` (`tipo` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_comprobante`
    FOREIGN KEY (`tipo`)
    REFERENCES `enbalde`.`TipoComprobantes` (`id_tipo_comprobantes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `enbalde`.`RegimenIvas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enbalde`.`RegimenIvas` (
  `id_regimen_iva` INT NOT NULL,
  `nombre` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id_regimen_iva`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `enbalde`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enbalde`.`Usuarios` (
  `id_usuarios` INT NOT NULL,
  `tipo_usuario` INT NOT NULL,
  `nombre` VARCHAR(40) NOT NULL,
  `apellido` VARCHAR(40) NOT NULL,
  `direccion` VARCHAR(40) NULL DEFAULT NULL,
  `regIva` INT NOT NULL,
  `observacion` VARCHAR(200) NULL DEFAULT NULL,
  `usuario` VARCHAR(40) NOT NULL,
  `pasword` VARCHAR(40) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuarios`),
  INDEX `fk_regiva_idx` (`regIva` ASC) VISIBLE,
  CONSTRAINT `fk_regiva`
    FOREIGN KEY (`regIva`)
    REFERENCES `enbalde`.`RegimenIvas` (`id_regimen_iva`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `enbalde`.`Envios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enbalde`.`Envios` (
  `id_envios` INT NOT NULL,
  `nombre` VARCHAR(40) NOT NULL,
  `monto` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id_envios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `enbalde`.`MovComprobantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enbalde`.`MovComprobantes` (
  `id_mov_coprob` INT NOT NULL,
  `nrocomprobante` CHAR(14) NOT NULL,
  `comprobante` CHAR(3) NOT NULL,
  `fecha` DATE NOT NULL,
  `usuario` INT NOT NULL,
  `neto` DOUBLE NULL DEFAULT NULL,
  `monto_iva` DOUBLE NULL DEFAULT NULL,
  `alicuota` FLOAT NULL DEFAULT NULL,
  `nogravado` DOUBLE NULL DEFAULT NULL,
  `total` DOUBLE NULL DEFAULT NULL,
  `envio` INT NOT NULL,
  PRIMARY KEY (`id_mov_coprob`),
  INDEX `fk_compro_idx` (`comprobante` ASC) VISIBLE,
  INDEX `fk_entidad_idx` (`usuario` ASC) VISIBLE,
  INDEX `fk_envio_idx` (`envio` ASC) VISIBLE,
  CONSTRAINT `fk_comprobante`
    FOREIGN KEY (`comprobante`)
    REFERENCES `enbalde`.`Comprobantes` (`id_comprobantes`),
  CONSTRAINT `fk_entidad`
    FOREIGN KEY (`usuario`)
    REFERENCES `enbalde`.`Usuarios` (`id_usuarios`),
  CONSTRAINT `fk_envio`
    FOREIGN KEY (`envio`)
    REFERENCES `enbalde`.`Envios` (`id_envios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `enbalde`.`DetMovComprobantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enbalde`.`DetMovComprobantes` (
  `id_det_mov_comrpro` INT NOT NULL,
  `id_mov` INT NOT NULL,
  `articulo` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `pre_unitario` DOUBLE NULL DEFAULT NULL,
  `alicuo` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id_det_mov_comrpro`),
  INDEX `fk_articulo_idx` (`articulo` ASC) VISIBLE,
  INDEX `fk_movCompro_idx` (`id_mov` ASC) VISIBLE,
  CONSTRAINT `fk_articulo`
    FOREIGN KEY (`articulo`)
    REFERENCES `enbalde`.`Articulos` (`id_articulos`),
  CONSTRAINT `fk_movComprobante`
    FOREIGN KEY (`id_mov`)
    REFERENCES `enbalde`.`MovComprobantes` (`id_mov_coprob`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `enbalde`.`Ofertas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enbalde`.`Ofertas` (
  `id_ofertas` INT NOT NULL,
  `porcentaje` FLOAT NOT NULL,
  `fecha_vencimiento` DATE NOT NULL,
  PRIMARY KEY (`id_ofertas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `enbalde`.`OfertaArticulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enbalde`.`OfertaArticulo` (
  `id_ofertaarticulos` INT NOT NULL,
  `id_articulos` INT NOT NULL,
  `id_ofertas` INT NOT NULL,
  PRIMARY KEY (`id_ofertaarticulos`),
  CONSTRAINT `fk_ofertaarticulo_articulo`
    FOREIGN KEY (`id_articulos`)
    REFERENCES `enbalde`.`Articulos` (`id_articulos`),
  CONSTRAINT `fk_ofertaarticulo_oferta`
    FOREIGN KEY (`id_ofertas`)
    REFERENCES `enbalde`.`Ofertas` (`id_ofertas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
