-- MySQL Script generated by MySQL Workbench
-- Tue Apr 11 14:57:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Identificadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Identificadores` (
  `numero` INT NOT NULL,
  `nombre` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoComprobantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoComprobantes` (
  `numero` INT NOT NULL,
  `nombre` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comprobantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comprobantes` (
  `codigo` CHAR(3) NOT NULL,
  `descripcion` VARCHAR(60) NOT NULL,
  `tipo` INT NOT NULL,
  `signo` CHAR(1) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_tipo_compro_idx` (`tipo` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_comprobante`
    FOREIGN KEY (`tipo`)
    REFERENCES `mydb`.`TipoComprobantes` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Provincias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Provincias` (
  `numero` INT NOT NULL,
  `nombre` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Localidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Localidades` (
  `numero` INT NOT NULL,
  `nombre` VARCHAR(40) NOT NULL,
  `codPos` VARCHAR(20) NULL,
  `provincia` INT NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_provin_idx` (`provincia` ASC) VISIBLE,
  CONSTRAINT `fk_provincia`
    FOREIGN KEY (`provincia`)
    REFERENCES `mydb`.`Provincias` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RegimenIvas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RegimenIvas` (
  `numero` INT NOT NULL,
  `nombre` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entidades` (
  `numero` INT NOT NULL,
  `nombre` VARCHAR(40) NOT NULL,
  `denominacion` VARCHAR(40) NOT NULL,
  `identificador` INT NOT NULL,
  `nro_identificador` VARCHAR(13) NOT NULL,
  `direccion` VARCHAR(40) NULL,
  `barrio` VARCHAR(40) NULL,
  `localidad` INT NOT NULL,
  `regIva` INT NOT NULL,
  `observacion` VARCHAR(200) NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_identi_idx` (`identificador` ASC) VISIBLE,
  INDEX `fk_locali_idx` (`localidad` ASC) VISIBLE,
  INDEX `fk_regiva_idx` (`regIva` ASC) VISIBLE,
  CONSTRAINT `fk_identificador`
    FOREIGN KEY (`identificador`)
    REFERENCES `mydb`.`Identificadores` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_localidad`
    FOREIGN KEY (`localidad`)
    REFERENCES `mydb`.`Localidades` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_regiva`
    FOREIGN KEY (`regIva`)
    REFERENCES `mydb`.`RegimenIvas` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `numero` INT NOT NULL,
  `nombre` VARCHAR(40) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `identificador` INT NOT NULL,
  `nro_identificador` VARCHAR(13) NULL,
  `usuario` VARCHAR(40) NOT NULL,
  `password` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_usua_identi_idx` (`identificador` ASC) VISIBLE,
  CONSTRAINT `fk_usua_identi`
    FOREIGN KEY (`identificador`)
    REFERENCES `mydb`.`Identificadores` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MovComprobantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MovComprobantes` (
  `id_comp` INT NOT NULL,
  `nrocomprobante` CHAR(14) NOT NULL,
  `compro` CHAR(3) NOT NULL,
  `fecha` DATE NOT NULL,
  `entidad` INT NOT NULL,
  `neto` DOUBLE NULL,
  `iva` DOUBLE NULL,
  `alicuota` FLOAT NULL,
  `nogravado` DOUBLE NULL,
  `total` DOUBLE NULL,
  `usuario` INT NOT NULL,
  PRIMARY KEY (`id_comp`),
  INDEX `fk_compro_idx` (`compro` ASC) VISIBLE,
  INDEX `fk_entidad_idx` (`entidad` ASC) VISIBLE,
  INDEX `fk_usuari_idx` (`usuario` ASC) VISIBLE,
  CONSTRAINT `fk_comprobante`
    FOREIGN KEY (`compro`)
    REFERENCES `mydb`.`Comprobantes` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entidad`
    FOREIGN KEY (`entidad`)
    REFERENCES `mydb`.`Entidades` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`Usuarios` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoArticulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoArticulos` (
  `numero` INT NOT NULL,
  `nombre` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Presentaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Presentaciones` (
  `numero` INT NOT NULL,
  `nombre` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UnidadMedidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UnidadMedidas` (
  `numero` INT NOT NULL,
  `nombre` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Articulos` (
  `codigo` VARCHAR(20) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `cod_barras` VARCHAR(20) NULL,
  `tipo` INT NOT NULL,
  `precio` DOUBLE GENERATED ALWAYS AS () VIRTUAL,
  `costo` DOUBLE NOT NULL,
  `uni_medida` INT NOT NULL,
  `presentacion` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_tipo_art_idx` (`tipo` ASC) VISIBLE,
  INDEX `fk_presen_idx` (`presentacion` ASC) VISIBLE,
  INDEX `fk_unimed_idx` (`uni_medida` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_articulo`
    FOREIGN KEY (`tipo`)
    REFERENCES `mydb`.`TipoArticulos` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_presentacion`
    FOREIGN KEY (`presentacion`)
    REFERENCES `mydb`.`Presentaciones` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_unimedidad`
    FOREIGN KEY (`uni_medida`)
    REFERENCES `mydb`.`UnidadMedidas` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DetMovComprobantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DetMovComprobantes` (
  `id_det` INT NOT NULL,
  `id_mov` INT NOT NULL,
  `articulo` VARCHAR(20) NOT NULL,
  `cantidad` FLOAT NULL,
  `pre_unitario` DOUBLE NULL,
  `alicuo` FLOAT NULL,
  PRIMARY KEY (`id_det`),
  INDEX `fk_articulo_idx` (`articulo` ASC) VISIBLE,
  INDEX `fk_movCompro_idx` (`id_mov` ASC) VISIBLE,
  CONSTRAINT `fk_articulo`
    FOREIGN KEY (`articulo`)
    REFERENCES `mydb`.`Articulos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movComprobante`
    FOREIGN KEY (`id_mov`)
    REFERENCES `mydb`.`MovComprobantes` (`id_comp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
