export const constantes =
{
  MINIMO_NOMBRE_ARTICULO: 1,
  MAXIMO_NOMBRE_ARTICULO: 200,
  MINIMA_DESCRIPCION_ARTICULO: 1,
  MAXIMA_DESCRIPCION_ARTICULO: 200,
  MINIMO_NOMBRE_ENVIO: 1,
  MAXIMO_NOMBRE_ENVIO: 40,
  MINIMO_NOMBRE_OFERTA: 1,
  MAXIMO_NOMBRE_OFERTA: 40,
  MINIMO_NOMBRE_TIPO_ARTICULO: 1,
  MAXIMO_NOMBRE_TIPO_ARTICULO: 40,
  MINIMO_NOMBRE_USUARIO: 4, // 1 en base de datos
  MAXIMO_NOMBRE_USUARIO: 40, // 150 en base de datos
  MINIMO_APELLIDO_USUARIO: 3, // 1 en base de datos
  MAXIMO_APELLIDO_USUARIO: 40, // 150 en base de datos
  MINIMO_EMAIL_USUARIO: 6, // 1 en base de datos
  MAXIMO_EMAIL_USUARIO: 45, // sin limite en base de datos
  MINIMA_DIRECCION_USUARIO: 1,
  MAXIMA_DIRECCION_USUARIO: 40, // 100 en base de datos
  MINIMO_TELEFONO_USUARIO: 8, // 1 en base de datos
  MAXIMO_TELEFONO_USUARIO: 20,
  MINIMA_OBSERVACION_USUARIO: 1,
  MAXIMA_OBSERVACION_USUARIO: 200,
  MINIMO_USUARIO_USUARIO: 4, // 1 en base de datos
  MAXIMO_USUARIO_USUARIO: 20, // sin limite en base de datos
  MINIMA_CLAVE_USUARIO: 6,
  MAXIMA_CLAVE_USUARIO: 20,

  PATRON_EMAIL: /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
}
