ID_ARTICULO = 1
OTRO_ARTICULO_UID = 2
TITULO_ARTICULO = "Tacho de helado Frigor 1 litro"
TIPO_ARTICULO = 1
DESCRIPCION_ARTICULO = "Tacho de helado triple: frut"
PRECIO_ARTICULO = 1500
COSTO_ARTICULO = 1000
ALICUOTA_ARTICULO = 0.21
IMAGEN_ARTICULO = "imagen1.jpg"

ID_VENTA = 1
NUMERO_VENTA = 13
COMPROBANTE_VENTA = "001-0000001"
FECHA_VENTA = 2012/11/13
NETO_VENTA = 4235
MONTO_IVA_VENTA = 735
NO_GRAVADO_VENTA = 0
TOTAL_VENTA = 4235

ID_USUARIO = 1
NOMBRE_USUARIO = "Esteban"
APELLIDO_USUARIO = "Quito"
DNI_USUARIO = 34567890
USUARIO_USUARIO = "esteban"
CLAVE_USUARIO = "miclave"
EMAIL_USUARIO = "esteban.quito@gmail.com"

ID_ADMINISTRADOR = 2
NOMBRE_ADMINISTRADOR = "Carmen"
APELLIDO_ADMINISTRADOR = "Rodriguez"
DNI_ADMINISTRADOR = 24567890
USUARIO_ADMINISTRADOR = "admin"
CLAVE_ADMINISTRADOR = "clave_segura"
EMAIL_ADMINISTRADOR = "admin@enbalde.com"

ID_CLIENTE = 3
NOMBRE_CLIENTE = "Juan"
APELLIDO_CLIENTE = "Pérez"
DNI_CLIENTE = 40123456
USUARIO_CLIENTE = "jperez"
CLAVE_CLIENTE = "pass123"
EMAIL_CLIENTE = "jperez@gmail.com"

CANTIDAD_SELECCION = 3
TOTAL_SELECCION = PRECIO_ARTICULO * CANTIDAD_SELECCION
